version: '3.8'
services:
  fit-friends.postgres:
    image: postgres:14-alpine
    container_name: fit-friends.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - fit-friends.postgres:/var/lib/postgresql/data
    networks:
      - fit-friends.network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_ROOT_USERNAME} -d ${POSTGRES_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    

  fit-friends.pgadmin:
    image: dpage/pgadmin4
    container_name: fit-friends.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "unknown@mail.local"
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - ${PGADMIN_DB_PORT}:80
    networks:
      - fit-friends.network


  fit-friends.smtp.maildev:
    image: maildev/maildev
    container_name: fit-friends.smtp.maildev
    ports:
      - ${MAIL_UI_PORT}:1080  
      - ${MAIL_SMTP_PORT}:1025
    networks:
      - fit-friends.network
    environment:
      - SMTP_USER=${MAIL_USERNAME}
      - SMTP_PASS=${MAIL_PASSWORD}
    volumes:
      - maildev-data:/maildev/data

  fitfriends.container:
    container_name: fitfriends.container
    depends_on:
     - fit-friends.postgres
    restart: always
    image: fitfriends-backend:latest
    env_file:
      - app.prod.env
    ports: 
      - 3333:3333
    networks:
      - fit-friends.network
    

volumes:
  fit-friends.postgres:
  maildev-data:

networks:
  fit-friends.network:
      driver: bridge