version: '3.8'
services:
  fit-friends.postgres:
    image: postgres:14-alpine
    container_name: fit-friends.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - fit-friends.postgres:/var/lib/postgresql/data
    networks:
      - fit-friends
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_ROOT_USERNAME} -d ${POSTGRES_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    

  fit-friends.pgadmin:
    image: dpage/pgadmin4
    container_name: fit-friends.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "unknown@mail.local"
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - ${PGADMIN_DB_PORT}:80
    networks:
      - fit-friends


  fit-friends.notify.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: fit-friends.notify.rabbitmq
    ports:
      - 2088:15672
      - ${RABBIT_PORT}:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  fit-friends.postgres:

networks:
  fit-friends:
      driver: bridge