@user1 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJuYW1lIjoiVXNlck9uZSIsImVtYWlsIjoidXNlcjRAbWFpbC5sb2NhbCIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjk5NzI2NTE3LCJleHAiOjE2OTk4MTI5MTd9.ptI2MpnLthsHi7bDE_bz61BkC-ZnzQ152sRZjlpwAxE
@user2 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5hbWUiOiJVc2VyVHdvIiwiZW1haWwiOiJ1c2VyMkBtYWlsLmxvY2FsIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE2OTg2OTM3MjEsImV4cCI6MTY5ODc4MDEyMX0.QmISBWF2Jo-2xurspDnw69vs_UIXEKfyj_d6928Cxkk

@user3 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsIm5hbWUiOiJVc2VyVGhyZWUiLCJlbWFpbCI6InVzZXIzQG1haWwubG9jYWwiLCJyb2xlIjoiVXNlciIsImlhdCI6MTY5ODY5Mzc0MCwiZXhwIjoxNjk4NzgwMTQwfQ._QH28zDovULIAa_3VMubXGrnJLJZ7IIdAnY2jXSER6o

@trainer1 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsIm5hbWUiOiJUcmFpbmVyT25lIiwiZW1haWwiOiJ0cmFpbmVyMUBtYWlsLmxvY2FsIiwicm9sZSI6IlRyYWluZXIiLCJpYXQiOjE2OTg3NDk0NDgsImV4cCI6MTY5ODgzNTg0OH0.vMtuVDW4fAueBhes8MD34PVrZ3yshfZ_guZfP5cgD4w
# create reply
POST http://localhost:4000/api/replies/create HTTP/1.1
Authorization: {{user1}}
Content-Type: application/json

{
  "trainingId": 1,
  "text": "супер информативный отзыв по тренировки, который должен иметь длину от 100 до 1024 символов и оставляться к только к существующей тренировке",
  "rating": 3
}
###

# get training replies
GET http://localhost:4000/api/replies/list/1
Authorization: {{user1}}
###