@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI4LCJuYW1lIjoiVHJhaW5lck9uZSIsImVtYWlsIjoidHJhaW5lcjhAbWFpbC5sb2NhbCIsInJvbGUiOiJUcmFpbmVyIiwiaWF0IjoxNjk5NzIyNzQzLCJleHAiOjE2OTk4MDkxNDN9.eOcyUDIA_ZevOqI6GkXzUj_lvDvakKjYr3Yri8Va67M
#Upload user avatar
POST http://localhost:4000/api/static/upload/avatar HTTP/1.1
# Authorization: {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="nafik.jpg"
Content-Type: image/jpeg

< Q:/images/nafik.jpg

--boundary--

###

#Upload trainer certificate
POST http://localhost:4000/api/static/upload/certificate HTTP/1.1
# Authorization: {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="certificate"; filename="certificate.pdf"
Content-Type: application/pdf

< Q:/images/Оставьте брезгливость - съешьте лягушку.pdf

--boundary--

###

#Upload video training
POST http://localhost:4000/api/static/upload/training-video HTTP/1.1
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="training-video"; filename="3.avi"
Content-Type: video/avi

< Q:/images/3.avi

--boundary--

###