@trainer1 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsIm5hbWUiOiJUcmFpbmVyT25lIiwiZW1haWwiOiJ0cmFpbmVyMUBtYWlsLmxvY2FsIiwicm9sZSI6IlRyYWluZXIiLCJpYXQiOjE2OTg4MzA4MjUsImV4cCI6MTY5ODkxNzIyNX0.DQH5lpEy3egod5ZA-d1yHzoM1t7xKFNHrwRgI40yEas
@trainer2 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsIm5hbWUiOiJUcmFpbmVyVHdvIiwiZW1haWwiOiJ0cmFpbmVyMkBtYWlsLmxvY2FsIiwicm9sZSI6IlRyYWluZXIiLCJpYXQiOjE2OTg4NzQ3MDgsImV4cCI6MTY5ODk2MTEwOH0.RfaZiVXCZBQ_H3g-AmTuKqlbPXFUhscpeoj-7vvPYS8

@trainer3 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsIm5hbWUiOiJUcmFpbmVyVGhyZWUiLCJlbWFpbCI6InRyYWluZXIzQG1haWwubG9jYWwiLCJyb2xlIjoiVHJhaW5lciIsImlhdCI6MTY5ODg3NDc0NCwiZXhwIjoxNjk4OTYxMTQ0fQ.O5Wqg4SI6O5VcAD5sgD8K4hp8NNRwSzC-HJIDRsi4bU
#create new training
POST http://localhost:4000/api/trainings/create HTTP/1.1
Authorization: {{trainer3}}
Content-Type: application/json

{
  "title": "title",
  "fitnessLevel": "Pro",
  "trainingDuration": "FiftyToEightyMinutes",
  "trainingType": "Stretching",
  "price": 200,
  "caloriesToBurn": 1001,
  "description": "Описание тренировки",
  "gender": "Male",
  "video": "4eb6c4d9-b7d4-49f0-9f36-9d4c331f6c29.avi",
  "isSpecialOffer": false
}

###

# get training info
GET http://localhost:4000/api/trainings/details/1 HTTP/1.1
Authorization: {{trainer1}}
###

# update training info
PATCH http://localhost:4000/api/trainings/update/6 HTTP/1.1
Authorization: {{trainer1}}
Content-Type: application/json

{
  "video": "/4eb6c4d9-b7d4-49f0-9f36-9d4c331f6c29.avi"
}
###

#
GET http://localhost:4000/api/trainings/?sort=price&sortDirection=asc&trainingType=Yoga HTTP/1.1
Authorization: {{trainer1}}

###