@user1 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJuYW1lIjoi0JLQu9Cw0LTQuNGB0LvQsNCyIiwiZW1haWwiOiJhbHlzaGEud2Fsa2VyQGpvaG5zLmJpeiIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjk5MzA4OTMzLCJleHAiOjE2OTkzOTUzMzN9.G-8XHoq84NPRe3ECAw5zKN8rkTOP9xP-l_dUYMjzTQY
@user2 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5hbWUiOiJVc2VyVHdvIiwiZW1haWwiOiJ1c2VyMkBtYWlsLmxvY2FsIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE2OTg2OTM3MjEsImV4cCI6MTY5ODc4MDEyMX0.QmISBWF2Jo-2xurspDnw69vs_UIXEKfyj_d6928Cxkk

@user3 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsIm5hbWUiOiLQodCw0LLQtdC70LjQuSIsImVtYWlsIjoiaW5hZGVyQGh5YXR0LmNvbSIsInJvbGUiOiJUcmFpbmVyIiwiaWF0IjoxNjk5MzExMTc2LCJleHAiOjE2OTkzOTc1NzZ9.M4YiYlttkDoAQylUtQPak0Prk5AN6dLg7cSls8iE9Z8

@me = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUxLCJuYW1lIjoiZnJvbnRVc2VyIiwiZW1haWwiOiIyODYwMDU4QG1haWwucnUiLCJyb2xlIjoiVXNlciIsImlhdCI6MTcwMjU4MzI5OCwiZXhwIjoxNzAyNjY5Njk4fQ.saFiMBwu_fFxswYzk2U9fr5q9yfxi4jkKoA-93Zhld4
@friendUser = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5hbWUiOiLQktC70LDQtNC40YHQu9Cw0LIiLCJlbWFpbCI6ImhxcmxndXptNUBob3RtYWlsLmNvbSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzAyNDE1OTYxLCJleHAiOjE3MDI1MDIzNjF9.RDf2qArp_DQaCEa8VcxkVa29ZmMnfbrQYURQEDvPiiQ
# Create Training Request
POST http://localhost:4000/api/training-requests/create/5 HTTP/1.1
Authorization: {{me}}

###

#Update Training Request
PATCH http://localhost:4000/api/training-requests/update HTTP/1.1
Authorization: {{friendUser}}
Content-Type: application/json

{
  "id": "4339a582-fec1-4e0c-9f5e-5c6789cd2333",
  "status": "Accepted"
}

###
