@user1 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJuYW1lIjoi0JLQu9Cw0LTQuNGB0LvQsNCyIiwiZW1haWwiOiJhbHlzaGEud2Fsa2VyQGpvaG5zLmJpeiIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjk5MzA4OTMzLCJleHAiOjE2OTkzOTUzMzN9.G-8XHoq84NPRe3ECAw5zKN8rkTOP9xP-l_dUYMjzTQY
@user2 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5hbWUiOiJVc2VyVHdvIiwiZW1haWwiOiJ1c2VyMkBtYWlsLmxvY2FsIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE2OTg2OTM3MjEsImV4cCI6MTY5ODc4MDEyMX0.QmISBWF2Jo-2xurspDnw69vs_UIXEKfyj_d6928Cxkk

@user3 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsIm5hbWUiOiLQodCw0LLQtdC70LjQuSIsImVtYWlsIjoiaW5hZGVyQGh5YXR0LmNvbSIsInJvbGUiOiJUcmFpbmVyIiwiaWF0IjoxNjk5MzExMTc2LCJleHAiOjE2OTkzOTc1NzZ9.M4YiYlttkDoAQylUtQPak0Prk5AN6dLg7cSls8iE9Z8

# Create Training Request
POST http://localhost:4000/api/training-requests/create/3 HTTP/1.1
Authorization: {{user1}}

###

#Update Training Request
PATCH http://localhost:4000/api/training-requests/update HTTP/1.1
Authorization: {{user2}}
Content-Type: application/json

{
  "requestId": "be3aad11-d80f-4c87-92c6-3b6be0a85969",
  "status": "Declined"
}

###
