@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsIm5hbWUiOiLQodCw0LLQtdC70LjQuSIsImVtYWlsIjoiaW5hZGVyQGh5YXR0LmNvbSIsInJvbGUiOiJUcmFpbmVyIiwiaWF0IjoxNjk5MzExMTc2LCJleHAiOjE2OTkzOTc1NzZ9.M4YiYlttkDoAQylUtQPak0Prk5AN6dLg7cSls8iE9Z8
#get user messages
GET http://localhost:4000/api/messages HTTP/1.1
Authorization: {{token}}

###

#delete user message
DELETE http://localhost:4000/api/messages/66bce12e-45a8-410c-991f-7254db89f6be HTTP/1.1
Authorization: {{token}}

###