@me = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsIm5hbWUiOiJmcm9udFUiLCJlbWFpbCI6IkRpZU15R29kQGdtYWlsLmNvbSIsInJvbGUiOiJUcmFpbmVyIiwiaWF0IjoxNzAxMjg3ODk4LCJleHAiOjE3MDEyODg3OTh9.IDVCgZuP2Tgnz74F1AeXHsHn3QK2NLbDrrtYcrJjrvg
#get user messages
GET http://localhost:4000/api/messages HTTP/1.1
Authorization: {{me}}

###

#delete user message
DELETE http://localhost:4000/api/messages/66bce12e-45a8-410c-991f-7254db89f6be HTTP/1.1
Authorization: {{me}}

###