@me = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUxLCJuYW1lIjoiZnJvbnRVc2VyIiwiZW1haWwiOiIyODYwMDU4QG1haWwucnUiLCJyb2xlIjoiVXNlciIsImlhdCI6MTcwMjQxMDQ3MywiZXhwIjoxNzAyNDk2ODczfQ.f4C0S64Sop--P8f8lsESyl8wmYhwlUhOpod608vh6Ao
#get user messages
GET http://localhost:4000/api/messages HTTP/1.1
Authorization: {{me}}

###

#delete user message
DELETE http://localhost:4000/api/messages/66bce12e-45a8-410c-991f-7254db89f6be HTTP/1.1
Authorization: {{me}}

###