
@trainerToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsIm5hbWUiOiJOYW1l0KLRgNC10L3QtdGA0LAiLCJlbWFpbCI6InRlc3QxOEBtYWlsLmxvY2FsIiwicm9sZSI6IlRyYWluZXIiLCJpYXQiOjE2OTg2NjM4MDksImV4cCI6MTY5ODc1MDIwOX0.AQ2_50lsDSmm9jrXIrYezpQ15Emt0UsgGjriw_E60Tk
@userToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJuYW1lIjoiTmFtZdCu0LfQtdGA0LAiLCJlbWFpbCI6InRlczZAbWFpbC5sb2NhbCIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjk4MzQ4MDQ3LCJleHAiOjE2OTg0MzQ0NDd9.WkXj54GtTxd8vSKIpIsbYhbFg-l5RbRSES77lVEWH94
@userToken2 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0MkBtYWlsLmxvY2FsIiwicm9sZSI6IlRyYWluZXIiLCJpYXQiOjE2OTgzNDg1MDksImV4cCI6MTY5ODQzNDkwOX0.lKvKVKa3PpVwLGhQQp8ntfxSx8eEhdw8-cNFV4WYBPk
# get user info
GET  http://localhost:4000/api/users/details/3 HTTP/1.1

###

# update user profile
PATCH http://localhost:4000/api/users/details/5 HTTP/1.1
Authorization: {{userToken}}
Content-Type: application/json

{
  "avatar": "test.jpg",
  "trainerProfile": {
    "certificates": "e17be906-322b-429f-8c68-93588ce49410.pdf"
  }
}

###

# get users
Get http://localhost:4000/api/users?location=Udelnaya&fitnessLevel=Beginner,Amateur&trainingType=Boxing,Yoga HTTP/1.1
Authorization: {{trainerToken}}
###

# add friend
PATCH  http://localhost:4000/api/users/friends/add/5 HTTP/1.1
Authorization: {{userToken}}
###

# remove friend
PATCH http://localhost:4000/api/users/friends/remove/5 HTTP/1.1
Authorization: {{userToken}}
###

# get friendlist
GET  http://localhost:4000/api/users/friends/ HTTP/1.1
Authorization: {{userToken2}}
###