@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsIm5hbWUiOiJOYW1l0KLRgNC10L3QtdGA0LAiLCJlbWFpbCI6InRlc3QyQG1haWwubG9jYWwiLCJyb2xlIjoiVHJhaW5lciIsImlhdCI6MTY5NzczNzI1MywiZXhwIjoxNjk3ODIzNjUzfQ.jLIkXdNOuADxNgvvLl2srM67VPVD-Vy8RBSg5Fz_3Qs

# get user info
GET  http://localhost:4000/api/users/3 HTTP/1.1

###

# update user profile
PATCH http://localhost:4000/api/users/5 HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "name": "test",
  "trainerProfile": {
    "readyForWorkout": true
  }
}


###