
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0MkBtYWlsLmxvY2FsIiwicm9sZSI6IlRyYWluZXIiLCJpYXQiOjE2OTc5OTIxNTIsImV4cCI6MTY5ODA3ODU1Mn0.EsuXNhe3zQUHSoAPicCEzmObRCM_BkuD8TudHt1mRzk

# get user info
GET  http://localhost:4000/api/users/3 HTTP/1.1

###

# update user profile
PATCH http://localhost:4000/api/users/5 HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "name": "test",
  "trainerProfile": {
    "readyForWorkout": true
  }
}

###

# get users
Get http://localhost:4000/api/users?location=Udelnaya&fitnessLevel=Beginner,Amateur&trainingType=Boxing,Yoga HTTP/1.1
Authorization: {{token}}
###